// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq08f4lHeGZeg5ZTu99IKRUfXAckrlk98',
    appId: '1:764302595683:web:5fd4c53bfdc0f1d5e84a56',
    messagingSenderId: '764302595683',
    projectId: 'cet168-quiz-app',
    authDomain: 'cet168-quiz-app.firebaseapp.com',
    storageBucket: 'cet168-quiz-app.firebasestorage.app',
    measurementId: 'G-HYNBHQHTN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgEC60qjYr364ueOUqHrybNEz7Yh7u-M',
    appId: '1:764302595683:android:06b141ec15b1a1b9e84a56',
    messagingSenderId: '764302595683',
    projectId: 'cet168-quiz-app',
    storageBucket: 'cet168-quiz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQf2NRz9NqP5D6f5hEwWMpjgcOnf1CNNM',
    appId: '1:764302595683:ios:f0e53a26b03cbb79e84a56',
    messagingSenderId: '764302595683',
    projectId: 'cet168-quiz-app',
    storageBucket: 'cet168-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.cet168quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQf2NRz9NqP5D6f5hEwWMpjgcOnf1CNNM',
    appId: '1:764302595683:ios:f0e53a26b03cbb79e84a56',
    messagingSenderId: '764302595683',
    projectId: 'cet168-quiz-app',
    storageBucket: 'cet168-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.cet168quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq08f4lHeGZeg5ZTu99IKRUfXAckrlk98',
    appId: '1:764302595683:web:708a752ec33f3317e84a56',
    messagingSenderId: '764302595683',
    projectId: 'cet168-quiz-app',
    authDomain: 'cet168-quiz-app.firebaseapp.com',
    storageBucket: 'cet168-quiz-app.firebasestorage.app',
    measurementId: 'G-D4MKJVP5WF',
  );
}
